version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"
    depends_on:
      - maildev
    environment:
      - EMAIL_HOST=maildev
      - EMAIL_PORT=1025

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"  
      - "1025:1025"  