# Generated by Django 5.1.5 on 2025-03-02 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_remove_document_document_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
