# Generated by Django 5.1.5 on 2025-03-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents/'),
        ),
    ]
